/**
 * Card component for @box-model/rsd
 *
 * Container component demonstrating composition with children.
 * Uses StyleX tokens generated by StyleDictionary for cross-platform compatibility.
 */
import { css, html } from 'react-strict-dom';
import {
  cardTokens,
  colorTextTokens,
  colorBackgroundTokens,
  motionTokens,
} from '../tokens/tokens.stylex';

export type CardVariant = 'elevated' | 'outlined' | 'filled';

export interface CardProps {
  /** Card content */
  children: React.ReactNode;
  /** Visual variant */
  variant?: CardVariant;
  /** Additional padding */
  padded?: boolean;
  /** Apply interactive hover affordance */
  interactive?: boolean;
}

const styles = css.create({
  base: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    gap: cardTokens.gap,
    borderRadius: 0,
    backgroundColor: cardTokens.background,
    color: colorTextTokens.primary,
    borderWidth: cardTokens.borderWidth,
    borderStyle: 'solid',
    borderColor: cardTokens.borderColor,
    boxShadow: cardTokens.shadowRest,
    transitionProperty: 'box-shadow',
    transitionDuration: motionTokens.durationFast,
    transitionTimingFunction: motionTokens.easingStandard,
    overflow: 'hidden',
  },
  interactive: {
    cursor: 'pointer',
  },
  interactiveShadow: {
    cursor: 'pointer',
    boxShadow: {
      default: cardTokens.shadowRest,
      ':hover': cardTokens.shadowHover,
      ':active': cardTokens.shadowHover,
    },
  },
  // Variants
  elevated: {
    backgroundColor: cardTokens.background,
    boxShadow: cardTokens.shadowRest,
  },
  outlined: {
    backgroundColor: cardTokens.background,
    boxShadow: 'none',
  },
  filled: {
    backgroundColor: colorBackgroundTokens.sunken,
    boxShadow: 'none',
  },
  // Modifiers
  padded: {
    // Use individual padding for React Native compatibility
    paddingTop: cardTokens.padding,
    paddingBottom: cardTokens.padding,
    paddingLeft: cardTokens.padding,
    paddingRight: cardTokens.padding,
  },
});

/**
 * Card component using React Strict DOM
 *
 * @example
 * ```tsx
 * <Card variant="elevated" padded>
 *   <h2>Card Title</h2>
 *   <p>Card content goes here.</p>
 * </Card>
 * ```
 */
export function Card({
  children,
  variant = 'elevated',
  padded = true,
  interactive = false,
}: CardProps) {
  const interactiveStyle = interactive
    ? variant === 'outlined' || variant === 'filled'
      ? styles.interactive
      : styles.interactiveShadow
    : null;

  return (
    <html.div
      style={[
        styles.base,
        styles[variant],
        padded && styles.padded,
        interactiveStyle,
      ]}
    >
      {children}
    </html.div>
  );
}

/**
 * Card Header component
 */
export interface CardHeaderProps {
  children: React.ReactNode;
}

const headerStyles = css.create({
  header: {
    display: 'flex',
    flexDirection: 'column',
    gap: cardTokens.gap,
  },
});

export function CardHeader({ children }: CardHeaderProps) {
  return <html.div style={headerStyles.header}>{children}</html.div>;
}

/**
 * Card Body component
 */
export interface CardBodyProps {
  children: React.ReactNode;
}

const bodyStyles = css.create({
  body: {
    display: 'flex',
    flexDirection: 'column',
    gap: cardTokens.gap,
  },
});

export function CardBody({ children }: CardBodyProps) {
  return <html.div style={bodyStyles.body}>{children}</html.div>;
}

/**
 * Card Footer component
 */
export interface CardFooterProps {
  children: React.ReactNode;
}

const footerStyles = css.create({
  footer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: cardTokens.gap,
  },
});

export function CardFooter({ children }: CardFooterProps) {
  return <html.div style={footerStyles.footer}>{children}</html.div>;
}

/**
 * Card Actions component
 */
export interface CardActionsProps {
  children: React.ReactNode;
}

const actionsStyles = css.create({
  actions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: cardTokens.gap,
  },
});

export function CardActions({ children }: CardActionsProps) {
  return <html.div style={actionsStyles.actions}>{children}</html.div>;
}
