// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './button';

declare global {
  interface HTMLElementTagNameMap {
    'button-box': import('./button').Button;
  }
}

