// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './columns';

declare global {
  interface HTMLElementTagNameMap {
    'columns-box': import('./columns').Columns;
  }
}

