/**
 * Tag component for @box-model/rsd
 *
 * Pills for metadata, statuses, and taxonomy chips.
 * Uses StyleX tokens generated by StyleDictionary for cross-platform compatibility.
 */
import { css, html } from 'react-strict-dom';
import {
  tagTokens,
  typographyRolesTokens,
  sizeTokens,
} from '../tokens/tokens.stylex';

export type TagVariant = 'neutral' | 'info' | 'success' | 'warning' | 'danger';

export interface TagProps {
  /** Tag content */
  children: React.ReactNode;
  /** Visual variant */
  variant?: TagVariant;
}

const styles = css.create({
  base: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: tagTokens.gap,
    // Use individual padding tokens for React Native compatibility
    paddingTop: tagTokens.paddingBlock,
    paddingBottom: tagTokens.paddingBlock,
    paddingLeft: tagTokens.paddingInline,
    paddingRight: tagTokens.paddingInline,
    fontFamily: typographyRolesTokens.captionFontFamily,
    fontWeight: typographyRolesTokens.captionFontWeight,
    fontSize: typographyRolesTokens.captionFontSize,
    lineHeight: typographyRolesTokens.captionLineHeight,
    letterSpacing: typographyRolesTokens.captionLetterSpacing,
    borderRadius: tagTokens.radius,
    borderWidth: sizeTokens.borderWidthHairline,
    borderStyle: 'solid',
    textTransform: 'uppercase',
  },
  // Variants
  neutral: {
    backgroundColor: tagTokens.neutralBackground,
    borderColor: tagTokens.neutralBorder,
    color: tagTokens.neutralText,
  },
  info: {
    backgroundColor: tagTokens.infoBackground,
    borderColor: tagTokens.infoBorder,
    color: tagTokens.infoText,
  },
  success: {
    backgroundColor: tagTokens.successBackground,
    borderColor: tagTokens.successBorder,
    color: tagTokens.successText,
  },
  warning: {
    backgroundColor: tagTokens.warningBackground,
    borderColor: tagTokens.warningBorder,
    color: tagTokens.warningText,
  },
  danger: {
    backgroundColor: tagTokens.dangerBackground,
    borderColor: tagTokens.dangerBorder,
    color: tagTokens.dangerText,
  },
});

/**
 * Tag component using React Strict DOM
 *
 * @example
 * ```tsx
 * <Tag variant="neutral">Label</Tag>
 * <Tag variant="success">Active</Tag>
 * ```
 */
export function Tag({
  children,
  variant = 'neutral',
}: TagProps) {
  return (
    <html.span
      style={[
        styles.base,
        styles[variant],
      ]}
    >
      {children}
    </html.span>
  );
}
