// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './wysiwyg';

declare global {
  interface HTMLElementTagNameMap {
    'wysiwyg-box': import('./wysiwyg').Wysiwyg;
  }
}

