// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './table';

declare global {
  interface HTMLElementTagNameMap {
    'table-box': import('./table').Table;
  }
}

