// This file is auto-generated by libs/web/generators/preact.ts. Do not modify manually.

import type { JSX as PreactJSX } from 'preact';

interface SignalLike<T> {
  value: T;
  peek(): T;
  subscribe(fn: (value: T) => void): () => void;
}
type Signalish<T> = T | SignalLike<T>;

type ComponentAttributeMap = {
  'alert-box': {
    'variant': Signalish<import('../alert/alert').Alert['variant'] | undefined>;
  };
  'banner-box': {
    'variant': Signalish<import('../banner/banner').Banner['variant'] | undefined>;
  };
  'button-box': {
    'size': Signalish<import('../button/button').Button['size'] | undefined>;
    'variant': Signalish<import('../button/button').Button['variant'] | undefined>;
  };
  'card-box': {
    'interactive': Signalish<import('../card/card').Card['interactive'] | undefined>;
  };
  'checkbox-group-box': {
    'legend': Signalish<import('../checkbox/checkbox').CheckboxGroup['legend'] | undefined>;
  };
  'close-control-box': {
    'label': Signalish<import('../close-control/close-control').CloseControl['label'] | undefined>;
  };
  'columns-box': {
    'gap': Signalish<import('../columns/columns').Columns['gap'] | undefined>;
    'min-width': Signalish<import('../columns/columns').Columns['minWidth'] | undefined>;
  };
  'dialog-box': {
    'no-backdrop-close': Signalish<import('../dialog/dialog').Dialog['noBackdropClose'] | undefined>;
    'open': Signalish<import('../dialog/dialog').Dialog['open'] | undefined>;
  };
  'divider-box': {
    'orientation': Signalish<import('../divider/divider').Divider['orientation'] | undefined>;
  };
  'drawer-box': {
    'no-backdrop-close': Signalish<import('../drawer/drawer').Drawer['noBackdropClose'] | undefined>;
    'open': Signalish<import('../drawer/drawer').Drawer['open'] | undefined>;
    'placement': Signalish<import('../drawer/drawer').Drawer['placement'] | undefined>;
  };
  'input-box': {
    'fullwidth': Signalish<import('../input/input').Input['fullwidth'] | undefined>;
  };
  'link-box': {
    'size': Signalish<import('../link/link').Link['size'] | undefined>;
    'variant': Signalish<import('../link/link').Link['variant'] | undefined>;
  };
  'list-box': {
    'ordered': Signalish<import('../list/list').List['ordered'] | undefined>;
  };
  'loading-box': {
    'label-visible': Signalish<import('../loading/loading').Loading['labelVisible'] | undefined>;
  };
  'markdown-box': {
    'linkify': Signalish<import('../markdown/markdown').Markdown['linkify'] | undefined>;
  };
  'progress-box': {
    'max': Signalish<import('../progress/progress').Progress['max'] | undefined>;
    'value': Signalish<import('../progress/progress').Progress['value'] | undefined>;
  };
  'radio-group-box': {
    'legend': Signalish<import('../radio/radio').RadioGroup['legend'] | undefined>;
  };
  'select-box': {
    'fullwidth': Signalish<import('../select/select').Select['fullwidth'] | undefined>;
  };
  'skeleton-box': {
    'animated': Signalish<import('../skeleton/skeleton').Skeleton['animated'] | undefined>;
    'height': Signalish<import('../skeleton/skeleton').Skeleton['height'] | undefined>;
    'width': Signalish<import('../skeleton/skeleton').Skeleton['width'] | undefined>;
  };
  'stat-box': {
    'delta': Signalish<import('../stat/stat').Stat['delta'] | undefined>;
    'show-trend-indicator': Signalish<import('../stat/stat').Stat['showTrendIndicator'] | undefined>;
    'trend': Signalish<import('../stat/stat').Stat['trend'] | undefined>;
    'value': Signalish<import('../stat/stat').Stat['value'] | undefined>;
  };
  'status-icon-box': {
    'label': Signalish<import('../status-icon/status-icon').StatusIcon['label'] | undefined>;
    'variant': Signalish<import('../status-icon/status-icon').StatusIcon['variant'] | undefined>;
  };
  'table-box': {
    'zebra': Signalish<import('../table/table').Table['zebra'] | undefined>;
  };
  'tag-box': {
    'variant': Signalish<import('../tag/tag').Tag['variant'] | undefined>;
  };
  'terminal-line-box': {
    'cursor': Signalish<import('../terminal/terminal-line').TerminalLine['cursor'] | undefined>;
    'variant': Signalish<import('../terminal/terminal-line').TerminalLine['variant'] | undefined>;
  };
  'textarea-box': {
    'fullwidth': Signalish<import('../textarea/textarea').Textarea['fullwidth'] | undefined>;
  };
  'toast-box': {
    'variant': Signalish<import('../toast/toast').Toast['variant'] | undefined>;
  };
  'tooltip-box': {
    'default-placement': Signalish<import('../tooltip/tooltip').Tooltip['defaultPlacement'] | undefined>;
    'label': Signalish<import('../tooltip/tooltip').Tooltip['label'] | undefined>;
  };
  'wysiwyg-box': {
    'value': Signalish<import('../wysiwyg/wysiwyg').Wysiwyg['value'] | undefined>;
  };
};

type ComponentTagName = keyof ComponentAttributeMap;
type HtmlTagName = keyof HTMLElementTagNameMap;
type BasePreactProps<Tag extends HtmlTagName> = PreactJSX.HTMLAttributes<
  HTMLElementTagNameMap[Tag]
>;

type ComponentIntrinsicElements = {
  [Tag in ComponentTagName]: [keyof ComponentAttributeMap[Tag]] extends [never]
    ? BasePreactProps<Tag>
    : Omit<BasePreactProps<Tag>, keyof ComponentAttributeMap[Tag]> &
        Partial<ComponentAttributeMap[Tag]>;
};

declare module 'preact/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'alert-box': ComponentIntrinsicElements['alert-box'];
      'banner-box': ComponentIntrinsicElements['banner-box'];
      'button-box': ComponentIntrinsicElements['button-box'];
      'card-box': ComponentIntrinsicElements['card-box'];
      'checkbox-group-box': ComponentIntrinsicElements['checkbox-group-box'];
      'close-control-box': ComponentIntrinsicElements['close-control-box'];
      'columns-box': ComponentIntrinsicElements['columns-box'];
      'dialog-box': ComponentIntrinsicElements['dialog-box'];
      'divider-box': ComponentIntrinsicElements['divider-box'];
      'drawer-box': ComponentIntrinsicElements['drawer-box'];
      'input-box': ComponentIntrinsicElements['input-box'];
      'link-box': ComponentIntrinsicElements['link-box'];
      'list-box': ComponentIntrinsicElements['list-box'];
      'loading-box': ComponentIntrinsicElements['loading-box'];
      'markdown-box': ComponentIntrinsicElements['markdown-box'];
      'progress-box': ComponentIntrinsicElements['progress-box'];
      'radio-group-box': ComponentIntrinsicElements['radio-group-box'];
      'select-box': ComponentIntrinsicElements['select-box'];
      'skeleton-box': ComponentIntrinsicElements['skeleton-box'];
      'stat-box': ComponentIntrinsicElements['stat-box'];
      'status-icon-box': ComponentIntrinsicElements['status-icon-box'];
      'table-box': ComponentIntrinsicElements['table-box'];
      'tag-box': ComponentIntrinsicElements['tag-box'];
      'terminal-line-box': ComponentIntrinsicElements['terminal-line-box'];
      'textarea-box': ComponentIntrinsicElements['textarea-box'];
      'toast-box': ComponentIntrinsicElements['toast-box'];
      'tooltip-box': ComponentIntrinsicElements['tooltip-box'];
      'wysiwyg-box': ComponentIntrinsicElements['wysiwyg-box'];
      'badge-box': BasePreactProps<'badge-box'>;
      'dialog-footer-box': BasePreactProps<'dialog-footer-box'>;
      'dialog-header-box': BasePreactProps<'dialog-header-box'>;
      'drawer-header-box': BasePreactProps<'drawer-header-box'>;
      'terminal-box': BasePreactProps<'terminal-box'>;
      'toolbar-box': BasePreactProps<'toolbar-box'>;
    }
    interface IntrinsicAttributes {
      'onclose'?: (event: CustomEvent<unknown>) => void;
      'oninput'?: (event: CustomEvent<unknown>) => void;
    }
  }
}
