// This file is auto-generated by libs/web/generators/solid.ts. Do not modify manually.

import type { JSX as SolidJSX } from 'solid-js/jsx-runtime';

type SolidIntrinsicElements = SolidJSX.IntrinsicElements;
type ComponentAttributeMap = {
  'alert-box': {
    'variant': import('../alert/alert').Alert['variant'];
  };
  'banner-box': {
    'variant': import('../banner/banner').Banner['variant'];
  };
  'button-box': {
    'size': import('../button/button').Button['size'];
    'variant': import('../button/button').Button['variant'];
  };
  'card-box': {
    'interactive': import('../card/card').Card['interactive'];
  };
  'checkbox-group-box': {
    'legend': import('../checkbox/checkbox').CheckboxGroup['legend'];
  };
  'close-control-box': {
    'label': import('../close-control/close-control').CloseControl['label'];
  };
  'columns-box': {
    'gap': import('../columns/columns').Columns['gap'];
    'min-width': import('../columns/columns').Columns['minWidth'];
  };
  'dialog-box': {
    'no-backdrop-close': import('../dialog/dialog').Dialog['noBackdropClose'];
    'open': import('../dialog/dialog').Dialog['open'];
  };
  'divider-box': {
    'orientation': import('../divider/divider').Divider['orientation'];
  };
  'drawer-box': {
    'no-backdrop-close': import('../drawer/drawer').Drawer['noBackdropClose'];
    'open': import('../drawer/drawer').Drawer['open'];
    'placement': import('../drawer/drawer').Drawer['placement'];
  };
  'input-box': {
    'fullwidth': import('../input/input').Input['fullwidth'];
  };
  'link-box': {
    'size': import('../link/link').Link['size'];
    'variant': import('../link/link').Link['variant'];
  };
  'list-box': {
    'ordered': import('../list/list').List['ordered'];
  };
  'loading-box': {
    'label-visible': import('../loading/loading').Loading['labelVisible'];
  };
  'markdown-box': {
    'linkify': import('../markdown/markdown').Markdown['linkify'];
  };
  'progress-box': {
    'max': import('../progress/progress').Progress['max'];
    'value': import('../progress/progress').Progress['value'];
  };
  'radio-group-box': {
    'legend': import('../radio/radio').RadioGroup['legend'];
  };
  'select-box': {
    'fullwidth': import('../select/select').Select['fullwidth'];
  };
  'skeleton-box': {
    'animated': import('../skeleton/skeleton').Skeleton['animated'];
    'height': import('../skeleton/skeleton').Skeleton['height'];
    'width': import('../skeleton/skeleton').Skeleton['width'];
  };
  'stat-box': {
    'delta': import('../stat/stat').Stat['delta'];
    'show-trend-indicator': import('../stat/stat').Stat['showTrendIndicator'];
    'trend': import('../stat/stat').Stat['trend'];
    'value': import('../stat/stat').Stat['value'];
  };
  'status-icon-box': {
    'label': import('../status-icon/status-icon').StatusIcon['label'];
    'variant': import('../status-icon/status-icon').StatusIcon['variant'];
  };
  'table-box': {
    'zebra': import('../table/table').Table['zebra'];
  };
  'tag-box': {
    'variant': import('../tag/tag').Tag['variant'];
  };
  'terminal-line-box': {
    'cursor': import('../terminal/terminal-line').TerminalLine['cursor'];
    'variant': import('../terminal/terminal-line').TerminalLine['variant'];
  };
  'textarea-box': {
    'fullwidth': import('../textarea/textarea').Textarea['fullwidth'];
  };
  'toast-box': {
    'variant': import('../toast/toast').Toast['variant'];
  };
  'tooltip-box': {
    'default-placement': import('../tooltip/tooltip').Tooltip['defaultPlacement'];
    'label': import('../tooltip/tooltip').Tooltip['label'];
  };
  'wysiwyg-box': {
    'value': import('../wysiwyg/wysiwyg').Wysiwyg['value'];
  };
};

type ComponentTagName = keyof ComponentAttributeMap;
type HtmlTagName = keyof HTMLElementTagNameMap;
type BaseSolidProps<Tag extends HtmlTagName> = Tag extends keyof SolidIntrinsicElements
  ? SolidIntrinsicElements[Tag]
  : SolidJSX.HTMLAttributes<HTMLElementTagNameMap[Tag]>;

type ComponentIntrinsicElements = {
  [Tag in ComponentTagName]: [keyof ComponentAttributeMap[Tag]] extends [never]
    ? BaseSolidProps<Tag>
    : Omit<BaseSolidProps<Tag>, keyof ComponentAttributeMap[Tag]> &
        Partial<ComponentAttributeMap[Tag]>;
};

declare module 'solid-js/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'alert-box': ComponentIntrinsicElements['alert-box'];
      'banner-box': ComponentIntrinsicElements['banner-box'];
      'button-box': ComponentIntrinsicElements['button-box'];
      'card-box': ComponentIntrinsicElements['card-box'];
      'checkbox-group-box': ComponentIntrinsicElements['checkbox-group-box'];
      'close-control-box': ComponentIntrinsicElements['close-control-box'];
      'columns-box': ComponentIntrinsicElements['columns-box'];
      'dialog-box': ComponentIntrinsicElements['dialog-box'];
      'divider-box': ComponentIntrinsicElements['divider-box'];
      'drawer-box': ComponentIntrinsicElements['drawer-box'];
      'input-box': ComponentIntrinsicElements['input-box'];
      'link-box': ComponentIntrinsicElements['link-box'];
      'list-box': ComponentIntrinsicElements['list-box'];
      'loading-box': ComponentIntrinsicElements['loading-box'];
      'markdown-box': ComponentIntrinsicElements['markdown-box'];
      'progress-box': ComponentIntrinsicElements['progress-box'];
      'radio-group-box': ComponentIntrinsicElements['radio-group-box'];
      'select-box': ComponentIntrinsicElements['select-box'];
      'skeleton-box': ComponentIntrinsicElements['skeleton-box'];
      'stat-box': ComponentIntrinsicElements['stat-box'];
      'status-icon-box': ComponentIntrinsicElements['status-icon-box'];
      'table-box': ComponentIntrinsicElements['table-box'];
      'tag-box': ComponentIntrinsicElements['tag-box'];
      'terminal-line-box': ComponentIntrinsicElements['terminal-line-box'];
      'textarea-box': ComponentIntrinsicElements['textarea-box'];
      'toast-box': ComponentIntrinsicElements['toast-box'];
      'tooltip-box': ComponentIntrinsicElements['tooltip-box'];
      'wysiwyg-box': ComponentIntrinsicElements['wysiwyg-box'];
      'badge-box': BaseSolidProps<'badge-box'>;
      'dialog-footer-box': BaseSolidProps<'dialog-footer-box'>;
      'dialog-header-box': BaseSolidProps<'dialog-header-box'>;
      'drawer-header-box': BaseSolidProps<'drawer-header-box'>;
      'terminal-box': BaseSolidProps<'terminal-box'>;
      'toolbar-box': BaseSolidProps<'toolbar-box'>;
    }
    interface IntrinsicAttributes {
      'onclose'?: (event: CustomEvent<unknown>) => void;
      'oninput'?: (event: CustomEvent<unknown>) => void;
    }
  }
}
