// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './radio';

declare global {
  interface HTMLElementTagNameMap {
    'radio-group-box': import('./radio').RadioGroup;
  }
}

