// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './input';

declare global {
  interface HTMLElementTagNameMap {
    'input-box': import('./input').Input;
  }
}

