import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { rm } from 'node:fs/promises';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const THEMES = ['box-model-ui'];
const DEFAULT_THEME = 'box-model-ui';
const ACTIVE_THEME = process.env.THEME ?? DEFAULT_THEME;

if (!THEMES.includes(ACTIVE_THEME)) {
  throw new Error(`Unknown theme "${ACTIVE_THEME}". Available themes: ${THEMES.join(', ')}`);
}

const toPosix = (value) => value.split(path.sep).join('/');
const buildPath = `${toPosix(path.join(__dirname, '../../dist/libs/tokens/'))}/`;

/**
 * Convert token name to camelCase variable name
 * e.g., "component-button-font-family" -> "fontFamily"
 * Also handles numeric suffixes: "alpha-02" -> "alpha02", "font-size-2xl" -> "fontSize2xl"
 */
function toCamelCase(str) {
  // First, convert hyphens followed by letters to camelCase
  let result = str.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
  // Then, remove any remaining hyphens before numbers
  result = result.replace(/-(\d)/g, '$1');
  return result;
}

/**
 * Custom format for React Strict DOM / StyleX
 * Generates css.defineVars() calls grouped by token category
 */
function formatStyleX({ dictionary }) {
  const groups = {};

  // Group tokens by their top-level category
  for (const token of dictionary.allTokens) {
    const parts = token.path;
    let groupName;
    let varName;

    if (parts[0] === 'component') {
      // component.button.fontSize -> group: button, var: fontSize
      groupName = parts[1];
      varName = toCamelCase(parts.slice(2).join('-'));
    } else if (parts[0] === 'color') {
      // color.feedback.success.surface -> group: colorFeedback, var: successSurface
      if (parts[1] === 'feedback') {
        groupName = 'colorFeedback';
        varName = toCamelCase(parts.slice(2).join('-'));
      } else if (parts[1] === 'text' || parts[1] === 'background' || parts[1] === 'border') {
        groupName = 'color' + parts[1].charAt(0).toUpperCase() + parts[1].slice(1);
        varName = toCamelCase(parts.slice(2).join('-'));
      } else {
        groupName = 'color';
        varName = toCamelCase(parts.slice(1).join('-'));
      }
    } else if (parts[0] === 'typography') {
      if (parts[1] === 'roles') {
        groupName = 'typographyRoles';
        varName = toCamelCase(parts.slice(2).join('-'));
      } else {
        groupName = 'typography';
        varName = toCamelCase(parts.slice(1).join('-'));
      }
    } else if (parts[0] === 'motion') {
      groupName = 'motion';
      varName = toCamelCase(parts.slice(1).join('-'));
    } else if (parts[0] === 'space') {
      groupName = 'space';
      varName = toCamelCase(parts.slice(1).join('-'));
    } else if (parts[0] === 'shadow') {
      groupName = 'shadow';
      varName = toCamelCase(parts.slice(1).join('-'));
    } else if (parts[0] === 'size') {
      groupName = 'size';
      varName = toCamelCase(parts.slice(1).join('-'));
    } else {
      // Default grouping
      groupName = parts[0];
      varName = toCamelCase(parts.slice(1).join('-'));
    }

    if (!groups[groupName]) {
      groups[groupName] = {};
    }

    // Get the resolved value (use $value for SD4 or value for older versions)
    const resolvedValue = token.$value ?? token.value;

    // Format the value (quote strings, leave numbers as-is)
    let formattedValue;
    if (typeof resolvedValue === 'string') {
      // Escape single quotes in strings
      formattedValue = `'${resolvedValue.replace(/'/g, "\\'")}'`;
    } else {
      // StyleX defineVars expects string values for CSS variables.
      formattedValue = `'${String(resolvedValue)}'`;
    }

    groups[groupName][varName] = formattedValue;
  }

  // Generate output
  const lines = [
    '/**',
    ' * Do not edit directly, this file was auto-generated by StyleDictionary.',
    ' * React Strict DOM / StyleX compatible token definitions.',
    ' */',
    "import { css } from 'react-strict-dom';",
    '',
  ];

  // Sort group names for consistent output
  const sortedGroups = Object.keys(groups).sort();

  for (const groupName of sortedGroups) {
    const vars = groups[groupName];
    const exportName = groupName + 'Tokens';

    lines.push(`export const ${exportName} = css.defineVars({`);

    // Sort variable names within each group
    const sortedVars = Object.keys(vars).sort();
    for (const varName of sortedVars) {
      lines.push(`  ${varName}: ${vars[varName]},`);
    }

    lines.push('});');
    lines.push('');
  }

  return lines.join('\n');
}

export default {
  hooks: {
    parsers: {
      'tokens-js-module': {
        pattern: /\.js$/,
        parser: async ({ filePath }) => {
          const module = await import(pathToFileURL(filePath).href);
          return module.default ?? {};
        },
      },
    },
    formats: {
      'rsd/stylex': formatStyleX,
    },
    actions: {
      'clean-tokens-dist': {
        do: async () => {
          await rm(buildPath, { recursive: true, force: true });
        }
      },
    },
  },
  actionSets: {
    default: ['clean-tokens-dist'],
  },
  source: [
    toPosix(path.join(__dirname, 'src/raw/**/*.js')),
    toPosix(path.join(__dirname, 'src/semantic/**/*.js')),
    toPosix(path.join(__dirname, `src/theme/${ACTIVE_THEME}/**/*.js`)),
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath,
      files: [
        {
          destination: `${ACTIVE_THEME === DEFAULT_THEME ? '' : `${ACTIVE_THEME}.`}tokens.css`,
          format: 'css/variables',
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    scss: {
      transformGroup: 'scss',
      buildPath,
      files: [
        {
          destination: `${ACTIVE_THEME === DEFAULT_THEME ? '_' : `_${ACTIVE_THEME}.`}tokens.scss`,
          format: 'scss/variables',
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    js: {
      transformGroup: 'js',
      buildPath,
      files: [
        {
          destination: `${ACTIVE_THEME === DEFAULT_THEME ? '' : `${ACTIVE_THEME}.`}tokens.js`,
          format: 'javascript/es6',
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    ts: {
      transformGroup: 'js',
      buildPath,
      files: [
        {
          destination: `${ACTIVE_THEME === DEFAULT_THEME ? '' : `${ACTIVE_THEME}.`}tokens.d.ts`,
          format: 'typescript/es6-declarations',
          options: {
            outputStringLiterals: true,
          },
        },
      ],
    },
    rsd: {
      transformGroup: 'js',
      buildPath,
      files: [
        {
          destination: `${ACTIVE_THEME === DEFAULT_THEME ? '' : `${ACTIVE_THEME}.`}tokens.stylex.ts`,
          format: 'rsd/stylex',
        },
      ],
    },
  },
};
