// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './markdown';

declare global {
  interface HTMLElementTagNameMap {
    'markdown-box': import('./markdown').Markdown;
  }
}

