// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/blog" | "/blogs" | "/blog/:slug";
  };
  "./app.tsx": {
    id: "app";
    page: "/";
  };
  "./routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "./routes/blog.tsx": {
    id: "routes/blog";
    page: "/blog";
  };
  "./routes/blogs.tsx": {
    id: "routes/blogs";
    page: "/blogs";
  };
  "./routes/blog-article.tsx": {
    id: "routes/blog-article";
    page: "/blog/:slug";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "app": typeof import("./app/./app.tsx");
  "routes/about": typeof import("./app/./routes/about.tsx");
  "routes/blog": typeof import("./app/./routes/blog.tsx");
  "routes/blogs": typeof import("./app/./routes/blogs.tsx");
  "routes/blog-article": typeof import("./app/./routes/blog-article.tsx");
};