// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './card';

declare global {
  interface HTMLElementTagNameMap {
    'card-box': import('./card').Card;
  }
}

