// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './stat';

declare global {
  interface HTMLElementTagNameMap {
    'stat-box': import('./stat').Stat;
  }
}

