// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './banner';

declare global {
  interface HTMLElementTagNameMap {
    'banner-box': import('./banner').Banner;
  }
}

