// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './select';

declare global {
  interface HTMLElementTagNameMap {
    'select-box': import('./select').Select;
  }
}

