// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './progress';

declare global {
  interface HTMLElementTagNameMap {
    'progress-box': import('./progress').Progress;
  }
}

