// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './badge';

declare global {
  interface HTMLElementTagNameMap {
    'badge-box': import('./badge').Badge;
  }
}

