// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './skeleton';

declare global {
  interface HTMLElementTagNameMap {
    'skeleton-box': import('./skeleton').Skeleton;
  }
}

