// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './toast';

declare global {
  interface HTMLElementTagNameMap {
    'toast-box': import('./toast').Toast;
  }
}

