// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './textarea';

declare global {
  interface HTMLElementTagNameMap {
    'textarea-box': import('./textarea').Textarea;
  }
}

