import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  collectComponentMetadata,
  type ComponentMeta,
} from './component-metadata.js';

type ComponentInfo = ComponentMeta & {
  importPath: string;
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const TYPES_DIR = path.resolve(__dirname, '../src/types');
const OUTPUT_FILE = path.join(TYPES_DIR, 'preact.d.ts');

async function main() {
  const { components, events } = await collectComponentMetadata();
  const entries: ComponentInfo[] = components.map((component) => ({
    ...component,
    importPath: toRelativeImportPath(component.sourcePath),
  }));

  const content = buildTypingsFile(entries, events);

  await fs.mkdir(TYPES_DIR, { recursive: true });
  await fs.writeFile(OUTPUT_FILE, content, 'utf-8');

  console.log(`Generated Preact typings for ${entries.length} components.`);
}

function toRelativeImportPath(filePath: string): string {
  const withoutExtension = filePath.replace(/\.ts$/, '');
  const relativePath = path.relative(path.dirname(OUTPUT_FILE), withoutExtension).replace(/\\/g, '/');
  if (relativePath.startsWith('.')) {
    return relativePath;
  }
  return `./${relativePath}`;
}

function buildTypingsFile(components: ComponentInfo[], events: string[]): string {
  const componentsWithProps = components.filter((component) => component.properties.length > 0);
  const componentsWithoutProps = components.filter((component) => component.properties.length === 0);

  const lines: string[] = [
    '// This file is auto-generated by libs/web/generators/preact.ts. Do not modify manually.',
    '',
    "import type { JSX as PreactJSX } from 'preact';",
    '',
    'interface SignalLike<T> {',
    '  value: T;',
    '  peek(): T;',
    '  subscribe(fn: (value: T) => void): () => void;',
    '}',
    'type Signalish<T> = T | SignalLike<T>;',
    '',
    'type ComponentAttributeMap = {',
  ];

  for (const component of componentsWithProps) {
    lines.push(`  '${component.tagName}': {`);
    for (const property of component.properties) {
      lines.push(
        `    '${property.attributeName}': Signalish<import('${component.importPath}').${component.className}['${property.propertyName}'] | undefined>;`
      );
    }
    lines.push('  };');
  }

  lines.push('};');

  lines.push(
    '',
    'type ComponentTagName = keyof ComponentAttributeMap;',
    'type HtmlTagName = keyof HTMLElementTagNameMap;',
    'type BasePreactProps<Tag extends HtmlTagName> = PreactJSX.HTMLAttributes<',
    '  HTMLElementTagNameMap[Tag]',
    '>;',
    '',
    'type ComponentIntrinsicElements = {',
    '  [Tag in ComponentTagName]: [keyof ComponentAttributeMap[Tag]] extends [never]',
    '    ? BasePreactProps<Tag>',
    '    : Omit<BasePreactProps<Tag>, keyof ComponentAttributeMap[Tag]> &',
    '        Partial<ComponentAttributeMap[Tag]>;',
    '};',
    ''
  );

  lines.push(
    "declare module 'preact/jsx-runtime' {",
    '  namespace JSX {',
    '    interface IntrinsicElements {'
  );

  if (componentsWithProps.length) {
    for (const component of componentsWithProps) {
      lines.push(
        `      '${component.tagName}': ComponentIntrinsicElements['${component.tagName}'];`
      );
    }
  }

  if (componentsWithoutProps.length) {
    for (const component of componentsWithoutProps) {
      lines.push(`      '${component.tagName}': BasePreactProps<'${component.tagName}'>;`);
    }
  }
  lines.push('    }');

  lines.push('    interface IntrinsicAttributes {');
  if (events.length) {
    for (const eventName of events) {
      lines.push(`      'on${eventName}'?: (event: CustomEvent<unknown>) => void;`);
    }
  }
  lines.push('    }');
  lines.push('  }', '}', '');

  return `${lines.join('\n')}`;
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
