import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  collectComponentMetadata,
  type ComponentEvent,
  type ComponentMeta,
  type ComponentMetadataResult,
} from './component-metadata.js';

type ComponentInfo = ComponentMeta & {
  importPath: string;
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const TYPES_DIR = path.resolve(__dirname, '../src/types');
const OUTPUT_FILE = path.join(TYPES_DIR, 'preact.d.ts');

export async function emitPreactTypings(
  metadata?: ComponentMetadataResult
): Promise<void> {
  const { components } = metadata ?? (await collectComponentMetadata());
  const entries: ComponentInfo[] = components.map((component) => ({
    ...component,
    importPath: toRelativeImportPath(component.sourcePath),
  }));

  const content = buildTypingsFile(entries);
  await fs.mkdir(TYPES_DIR, { recursive: true });
  await fs.writeFile(OUTPUT_FILE, content, 'utf-8');
  console.log(`Generated Preact typings for ${entries.length} components.`);
}

function toRelativeImportPath(filePath: string): string {
  const withJavaScriptExtension = filePath.replace(/\.ts$/, '.js');
  const relativePath = path
    .relative(path.dirname(OUTPUT_FILE), withJavaScriptExtension)
    .replace(/\\/g, '/');
  if (relativePath.startsWith('.')) {
    return relativePath;
  }
  return `./${relativePath}`;
}

function renderEventType(
  component: ComponentInfo,
  event: ComponentEvent
): string {
  let typeText = event.type.text;
  const references = [...(event.type.references ?? [])].sort(
    (a, b) => b.start - a.start
  );

  for (const reference of references) {
    if (reference.package === 'global:') continue;
    if (
      reference.package !== undefined ||
      reference.module !== component.modulePath
    ) {
      return 'Event';
    }

    typeText =
      typeText.slice(0, reference.start) +
      `import('${component.importPath}').${reference.name}` +
      typeText.slice(reference.end);
  }

  return typeText;
}

function collectGlobalEventTypes(
  components: ComponentInfo[]
): Map<string, string[]> {
  const eventTypes = new Map<string, Set<string>>();

  for (const component of components) {
    for (const event of component.events) {
      const types = eventTypes.get(event.name) ?? new Set<string>();
      types.add(renderEventType(component, event));
      eventTypes.set(event.name, types);
    }
  }

  return new Map(
    [...eventTypes.entries()]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([name, types]) => [name, [...types].sort()])
  );
}

function buildTypingsFile(components: ComponentInfo[]): string {
  const componentsWithAttrs = components.filter(
    (component) =>
      component.properties.some((property) => property.attributeName) ||
      component.events.length > 0
  );
  const globalEventTypes = collectGlobalEventTypes(components);

  const lines: string[] = [
    '// This file is auto-generated by libs/web/generators/preact.ts. Do not modify manually.',
    '',
    "import type { JSX as PreactJSX } from 'preact';",
    '',
    'interface SignalLike<T> {',
    '  value: T;',
    '  peek(): T;',
    '  subscribe(fn: (value: T) => void): () => void;',
    '}',
    'type Signalish<T> = T | SignalLike<T>;',
    '',
    'type ComponentElementMap = {',
  ];

  for (const component of components) {
    lines.push(
      `  '${component.tagName}': import('${component.importPath}').${component.className};`
    );
  }

  lines.push('};', '', 'type ComponentAttributeMap = {');

  for (const component of componentsWithAttrs) {
    lines.push(`  '${component.tagName}': {`);
    for (const property of component.properties) {
      if (!property.attributeName) continue;
      lines.push(
        `    '${property.attributeName}': Signalish<import('${component.importPath}').${component.className}['${property.propertyName}'] | undefined>;`
      );
    }
    for (const event of component.events) {
      lines.push(
        `    'on${event.name}'?: (event: ${renderEventType(
          component,
          event
        )}) => void;`
      );
    }
    lines.push('  };');
  }

  lines.push('};');

  lines.push(
    '',
    'type ComponentTagName = keyof ComponentElementMap;',
    'type BasePreactProps<Tag extends ComponentTagName> = PreactJSX.HTMLAttributes<',
    '  ComponentElementMap[Tag]',
    '>;',
    '',
    'type ComponentIntrinsicElements = {',
    '  [Tag in ComponentTagName]: Tag extends keyof ComponentAttributeMap',
    '    ? [keyof ComponentAttributeMap[Tag]] extends [never]',
    '      ? BasePreactProps<Tag>',
    '      : Omit<BasePreactProps<Tag>, keyof ComponentAttributeMap[Tag]> &',
    '          Partial<ComponentAttributeMap[Tag]>',
    '    : BasePreactProps<Tag>;',
    '};',
    ''
  );

  lines.push(
    "declare module 'preact/jsx-runtime' {",
    '  namespace JSX {',
    '    interface DOMAttributes<Target extends EventTarget> {'
  );
  for (const [eventName, eventTypes] of globalEventTypes) {
    lines.push(
      `      'on${eventName}'?: (event: ${eventTypes
        .map((eventType) => `PreactJSX.TargetedEvent<Target, ${eventType}>`)
        .join(' | ')}) => void;`
    );
  }
  lines.push('    }', '    interface IntrinsicElements {');

  for (const component of components) {
    lines.push(
      `      '${component.tagName}': ComponentIntrinsicElements['${component.tagName}'];`
    );
  }
  lines.push('    }');
  lines.push('  }', '}', '');

  return `${lines.join('\n')}`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === __filename) {
  emitPreactTypings().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
