import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  collectComponentMetadata,
  type ComponentMeta,
  type ComponentMetadataResult,
} from './component-metadata.js';

type ComponentInfo = ComponentMeta & {
  importPath: string;
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const TYPES_DIR = path.resolve(__dirname, '../src/types');
const OUTPUT_FILE = path.join(TYPES_DIR, 'solid.d.ts');

export async function emitSolidTypings(metadata?: ComponentMetadataResult): Promise<void> {
  const { components, events } = metadata ?? (await collectComponentMetadata());
  const entries: ComponentInfo[] = components.map((component) => ({
    ...component,
    importPath: toRelativeImportPath(component.sourcePath),
  }));

  const content = buildTypingsFile(entries, events);
  await fs.mkdir(TYPES_DIR, { recursive: true });
  await fs.writeFile(OUTPUT_FILE, content, 'utf-8');
  console.log(`Generated Solid typings for ${entries.length} components.`);
}

function toRelativeImportPath(filePath: string): string {
  const withoutExtension = filePath.replace(/\.ts$/, '');
  const relativePath = path.relative(path.dirname(OUTPUT_FILE), withoutExtension).replace(/\\/g, '/');
  if (relativePath.startsWith('.')) {
    return relativePath;
  }
  return `./${relativePath}`;
}

function buildTypingsFile(components: ComponentInfo[], events: string[]): string {
  const componentsWithAttrs = components.filter((component) =>
    component.properties.some((property) => property.attributeName)
  );
  const componentsWithoutAttrs = components.filter(
    (component) => !component.properties.some((property) => property.attributeName)
  );

  const lines: string[] = [
    '// This file is auto-generated by libs/web/generators/solid.ts. Do not modify manually.',
    '',
    "import type { JSX as SolidJSX } from 'solid-js/jsx-runtime';",
    '',
    'type SolidIntrinsicElements = SolidJSX.IntrinsicElements;',
    'type ComponentAttributeMap = {',
  ];

  for (const component of componentsWithAttrs) {
    lines.push(`  '${component.tagName}': {`);
    for (const property of component.properties) {
      if (!property.attributeName) continue;
      lines.push(
        `    '${property.attributeName}': import('${component.importPath}').${component.className}['${property.propertyName}'];`
      );
    }
    lines.push('  };');
  }

  lines.push('};');

  lines.push(
    '',
    'type ComponentTagName = keyof ComponentAttributeMap;',
    'type HtmlTagName = keyof HTMLElementTagNameMap;',
    'type BaseSolidProps<Tag extends HtmlTagName> = Tag extends keyof SolidIntrinsicElements',
    '  ? SolidIntrinsicElements[Tag]',
    '  : SolidJSX.HTMLAttributes<HTMLElementTagNameMap[Tag]>;',
    '',
    'type ComponentIntrinsicElements = {',
    '  [Tag in ComponentTagName]: [keyof ComponentAttributeMap[Tag]] extends [never]',
    '    ? BaseSolidProps<Tag>',
    '    : Omit<BaseSolidProps<Tag>, keyof ComponentAttributeMap[Tag]> &',
    '        Partial<ComponentAttributeMap[Tag]>;',
    '};',
    ''
  );

  lines.push(
    "declare module 'solid-js/jsx-runtime' {",
    '  namespace JSX {',
    '    interface IntrinsicElements {'
  );

  for (const component of componentsWithAttrs) {
    lines.push(`      '${component.tagName}': ComponentIntrinsicElements['${component.tagName}'];`);
  }

  for (const component of componentsWithoutAttrs) {
    lines.push(`      '${component.tagName}': BaseSolidProps<'${component.tagName}'>;`);
  }
  lines.push('    }');

  lines.push('    interface IntrinsicAttributes {');
  for (const eventName of events) {
    lines.push(`      'on${eventName}'?: (event: CustomEvent<unknown>) => void;`);
  }
  lines.push('    }');
  lines.push('  }', '}', '');

  return `${lines.join('\n')}`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === __filename) {
  emitSolidTypings().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
