import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  collectComponentMetadata,
  type ComponentMeta,
  type ComponentMetadataResult,
} from './component-metadata.js';
import { isPublicLibraryEntryDirectory } from './library-entrypoints.js';

type DirectoryResult = {
  updated: boolean;
  name: string;
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const SRC_ROOT = path.resolve(__dirname, '../src');

const EXCLUDED_SUFFIXES = ['.spec.ts', '.stories.ts', '.test.ts'];

export async function emitTagNameMaps(
  metadata?: ComponentMetadataResult
): Promise<void> {
  const { components } = metadata ?? (await collectComponentMetadata());
  const byDirectory = new Map<string, ComponentMeta[]>();

  for (const component of components) {
    const list = byDirectory.get(component.directoryName) ?? [];
    list.push(component);
    byDirectory.set(component.directoryName, list);
  }

  const entries = await fs.readdir(SRC_ROOT, { withFileTypes: true });
  const updates: DirectoryResult[] = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const result = await processDirectory(
      entry.name,
      byDirectory.get(entry.name) ?? []
    );
    if (result) {
      updates.push(result);
    }
  }

  const rootUpdated = await emitRootIndex(
    updates.map((entry) => entry.name).filter(isPublicLibraryEntryDirectory)
  );

  if (updates.length) {
    const changed = updates
      .filter((entry) => entry.updated)
      .map((entry) => entry.name);
    if (rootUpdated) {
      changed.push('(root)');
    }
    if (changed.length) {
      console.log(`Updated tag maps for: ${changed.join(', ')}`);
    } else {
      console.log('Tag name map is up to date.');
    }
  }
}

async function emitRootIndex(directories: string[]): Promise<boolean> {
  const lines = [
    '// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.',
    '',
    ...directories
      .sort((a, b) => a.localeCompare(b))
      .map((directory) => `export * from './${directory}/index.js';`),
    '',
  ];
  const indexPath = path.join(SRC_ROOT, 'index.ts');
  const newContent = `${lines.join('\n')}\n`;
  const previousContent = await readFileIfExists(indexPath);

  if (previousContent === newContent) {
    return false;
  }

  await fs.writeFile(indexPath, newContent, 'utf-8');
  return true;
}

async function processDirectory(
  dirName: string,
  components: ComponentMeta[]
): Promise<DirectoryResult | undefined> {
  const directoryPath = path.join(SRC_ROOT, dirName);
  const directoryEntries = await fs.readdir(directoryPath, {
    withFileTypes: true,
  });

  const hasIndexFile = directoryEntries.some(
    (entry) => entry.isFile() && entry.name === 'index.ts'
  );

  if (!hasIndexFile) {
    return undefined;
  }

  const componentFiles = directoryEntries
    .filter(
      (entry) =>
        entry.isFile() &&
        entry.name.endsWith('.ts') &&
        entry.name !== 'index.ts' &&
        !EXCLUDED_SUFFIXES.some((suffix) => entry.name.endsWith(suffix))
    )
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));

  const exportLines = componentFiles.map(
    (fileName) => `export * from './${fileName.replace(/\.ts$/, '')}';`
  );

  const tagEntries = components
    .map((component) => ({
      tagName: component.tagName,
      className: component.className,
      importPath: `./${path
        .basename(component.sourcePath)
        .replace(/\.ts$/, '')}`,
    }))
    .sort((a, b) => a.tagName.localeCompare(b.tagName));

  const lines: string[] = [
    '// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.',
  ];

  if (exportLines.length) {
    lines.push('', ...exportLines);
  }

  if (tagEntries.length) {
    lines.push('', 'declare global {', '  interface HTMLElementTagNameMap {');
    for (const entry of tagEntries) {
      lines.push(
        `    '${entry.tagName}': import('${entry.importPath}').${entry.className};`
      );
    }
    lines.push('  }', '}', '');
  } else {
    lines.push('');
  }

  const indexPath = path.join(directoryPath, 'index.ts');
  const newContent = `${lines.join('\n')}\n`;
  const previousContent = await readFileIfExists(indexPath);

  const updated = previousContent !== newContent;
  if (updated) {
    await fs.writeFile(indexPath, newContent, 'utf-8');
  }

  return { updated, name: dirName };
}

async function readFileIfExists(filePath: string) {
  try {
    return await fs.readFile(filePath, 'utf-8');
  } catch {
    return undefined;
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === __filename) {
  emitTagNameMaps().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
