import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

type TagEntry = {
  tagName: string;
  className: string;
  importPath: string;
};

type DirectoryResult = {
  updated: boolean;
  name: string;
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const SRC_ROOT = path.resolve(__dirname, '../src');

const EXCLUDED_SUFFIXES = ['.spec.ts', '.stories.ts', '.test.ts'];

async function main() {
  const entries = await fs.readdir(SRC_ROOT, { withFileTypes: true });
  const updates: DirectoryResult[] = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) {
      continue;
    }

    const result = await processDirectory(entry.name);
    if (result) {
      updates.push(result);
    }
  }

  if (updates.length) {
    const changed = updates.filter((entry) => entry.updated).map((entry) => entry.name);
    if (changed.length) {
      console.log(`Updated tag maps for: ${changed.join(', ')}`);
    } else {
      console.log('Tag name map is up to date.');
    }
  }
}

async function processDirectory(dirName: string): Promise<DirectoryResult | undefined> {
  const directoryPath = path.join(SRC_ROOT, dirName);
  const directoryEntries = await fs.readdir(directoryPath, { withFileTypes: true });

  const hasIndexFile = directoryEntries.some(
    (entry) => entry.isFile() && entry.name === 'index.ts'
  );

  if (!hasIndexFile) {
    return undefined;
  }

  const componentFiles = directoryEntries
    .filter(
      (entry) =>
        entry.isFile() &&
        entry.name.endsWith('.ts') &&
        entry.name !== 'index.ts' &&
        !EXCLUDED_SUFFIXES.some((suffix) => entry.name.endsWith(suffix))
    )
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));

  const exportLines = componentFiles.map(
    (fileName) => `export * from './${fileName.replace(/\.ts$/, '')}';`
  );

  const tagEntries = (
    await Promise.all(
      componentFiles.map(async (fileName) => {
        const filePath = path.join(directoryPath, fileName);
        const contents = await fs.readFile(filePath, 'utf-8');
        const baseImportPath = `./${fileName.replace(/\.ts$/, '')}`;
        return extractTagEntries(contents, baseImportPath);
      })
    )
  )
    .flat()
    .sort((a, b) => a.tagName.localeCompare(b.tagName));

  const lines: string[] = [
    '// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.',
  ];

  if (exportLines.length) {
    lines.push('', ...exportLines);
  }

  if (tagEntries.length) {
    lines.push('', 'declare global {', '  interface HTMLElementTagNameMap {');
    for (const entry of tagEntries) {
      lines.push(
        `    '${entry.tagName}': import('${entry.importPath}').${entry.className};`
      );
    }
    lines.push('  }', '}', '');
  } else {
    lines.push('');
  }

  const indexPath = path.join(directoryPath, 'index.ts');
  const newContent = `${lines.join('\n')}\n`;
  const previousContent = await readFileIfExists(indexPath);

  const updated = previousContent !== newContent;
  if (updated) {
    await fs.writeFile(indexPath, newContent, 'utf-8');
  }

  return { updated, name: dirName };
}

async function readFileIfExists(filePath: string) {
  try {
    return await fs.readFile(filePath, 'utf-8');
  } catch (error) {
    return undefined;
  }
}

function extractTagEntries(fileContents: string, importPath: string): TagEntry[] {
  const tagConstants = new Map<string, string>();
  const constRegex = /export const (\w+)\s*=\s*(['"`])([^'"`]+)\2/g;
  let constMatch: RegExpExecArray | null;
  while ((constMatch = constRegex.exec(fileContents)) !== null) {
    const [, constName, , tagName] = constMatch;
    tagConstants.set(constName, tagName);
  }

  const customElementRegex = /@customElement\(([^)]+)\)\s*export class (\w+)/g;
  const tagEntries: TagEntry[] = [];
  let decoratorMatch: RegExpExecArray | null;

  while ((decoratorMatch = customElementRegex.exec(fileContents)) !== null) {
    const [, rawDecoratorArg, className] = decoratorMatch;
    const normalizedArg = rawDecoratorArg.trim();
    const tagName = resolveTagName(normalizedArg, tagConstants);

    if (!tagName) {
      continue;
    }

    tagEntries.push({
      tagName,
      className,
      importPath,
    });
  }

  return tagEntries;
}

function resolveTagName(
  rawDecoratorArg: string,
  tagConstants: Map<string, string>
): string | undefined {
  if (!rawDecoratorArg) {
    return undefined;
  }

  const isStringLiteral =
    (rawDecoratorArg.startsWith("'") && rawDecoratorArg.endsWith("'")) ||
    (rawDecoratorArg.startsWith('"') && rawDecoratorArg.endsWith('"')) ||
    (rawDecoratorArg.startsWith('`') && rawDecoratorArg.endsWith('`'));

  if (isStringLiteral) {
    return rawDecoratorArg.slice(1, -1);
  }

  return tagConstants.get(rawDecoratorArg);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
