// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './tooltip';

declare global {
  interface HTMLElementTagNameMap {
    'tooltip-box': import('./tooltip').Tooltip;
  }
}

