// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './toolbar';

declare global {
  interface HTMLElementTagNameMap {
    'toolbar-box': import('./toolbar').Toolbar;
  }
}

