// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './tag';

declare global {
  interface HTMLElementTagNameMap {
    'tag-box': import('./tag').Tag;
  }
}

