// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './alert';

declare global {
  interface HTMLElementTagNameMap {
    'alert-box': import('./alert').Alert;
  }
}

