// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './close-control';

declare global {
  interface HTMLElementTagNameMap {
    'close-control-box': import('./close-control').CloseControl;
  }
}

