// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './status-icon';

declare global {
  interface HTMLElementTagNameMap {
    'status-icon-box': import('./status-icon').StatusIcon;
  }
}

