// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './loading';

declare global {
  interface HTMLElementTagNameMap {
    'loading-box': import('./loading').Loading;
  }
}

