// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './checkbox';

declare global {
  interface HTMLElementTagNameMap {
    'checkbox-group-box': import('./checkbox').CheckboxGroup;
  }
}

