/**
 * Button component for @box-model/rsd
 *
 * Uses react-strict-dom patterns for cross-platform compatibility.
 * Uses StyleX tokens generated by StyleDictionary for cross-platform compatibility.
 */
import { css, html } from 'react-strict-dom';
import { Linking, Platform } from 'react-native';
import { buttonTokens } from '../tokens/tokens.stylex';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost';
export type ButtonSize = 'small' | 'medium' | 'large';

export interface ButtonProps {
  /** Button content */
  children: React.ReactNode;
  /** Click handler (ignored when href is provided) */
  onClick?: () => void;
  /** Visual variant */
  variant?: ButtonVariant;
  /** Button size */
  size?: ButtonSize;
  /** Disabled state */
  disabled?: boolean;
  /** URL for link-style button (renders as anchor) */
  href?: string;
  /** Link target (e.g., "_blank") */
  target?: '_self' | '_blank' | '_parent' | '_top';
  /** Link relationship (e.g., "noreferrer") */
  rel?: string;
}

const styles = css.create({
  base: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxSizing: 'border-box',
    borderWidth: '3px',
    borderColor: 'transparent',
    borderStyle: 'solid',
    fontFamily: buttonTokens.fontFamily,
    fontWeight: buttonTokens.fontWeight,
    letterSpacing: buttonTokens.letterSpacing,
    lineHeight: buttonTokens.lineHeight,
    fontSize: buttonTokens.fontSizeMd,
    // Use individual padding tokens for React Native compatibility
    paddingTop: buttonTokens.paddingBlockMd,
    paddingBottom: buttonTokens.paddingBlockMd,
    paddingLeft: buttonTokens.paddingInlineMd,
    paddingRight: buttonTokens.paddingInlineMd,
    borderRadius: 0,
    minHeight: buttonTokens.minHeightMd,
    gap: buttonTokens.gap,
    textAlign: 'center',
    textDecorationLine: 'none',
    cursor: 'pointer',
    transitionProperty: 'background-color',
    transitionDuration: buttonTokens.transitionDuration,
    transitionTimingFunction: buttonTokens.transitionEasing,
  },
  // Variants
  primary: {
    backgroundColor: {
      default: buttonTokens.primaryBackgroundRest,
      ':hover': buttonTokens.primaryBackgroundHover,
      ':active': buttonTokens.primaryBackgroundActive,
    },
    color: buttonTokens.primaryText,
  },
  secondary: {
    backgroundColor: {
      default: buttonTokens.secondaryBackgroundRest,
      ':hover': buttonTokens.secondaryBackgroundHover,
      ':active': buttonTokens.secondaryBackgroundActive,
    },
    color: buttonTokens.secondaryText,
  },
  ghost: {
    backgroundColor: {
      default: buttonTokens.tertiaryBackgroundRest,
      ':hover': buttonTokens.tertiaryBackgroundHover,
      ':active': buttonTokens.tertiaryBackgroundActive,
    },
    color: buttonTokens.tertiaryText,
  },
  // Sizes
  small: {
    paddingTop: buttonTokens.paddingBlockSm,
    paddingBottom: buttonTokens.paddingBlockSm,
    paddingLeft: buttonTokens.paddingInlineSm,
    paddingRight: buttonTokens.paddingInlineSm,
    fontSize: buttonTokens.fontSizeSm,
    minHeight: buttonTokens.minHeightSm,
  },
  medium: {
    paddingTop: buttonTokens.paddingBlockMd,
    paddingBottom: buttonTokens.paddingBlockMd,
    paddingLeft: buttonTokens.paddingInlineMd,
    paddingRight: buttonTokens.paddingInlineMd,
    fontSize: buttonTokens.fontSizeMd,
    minHeight: buttonTokens.minHeightMd,
  },
  large: {
    paddingTop: buttonTokens.paddingBlockLg,
    paddingBottom: buttonTokens.paddingBlockLg,
    paddingLeft: buttonTokens.paddingInlineLg,
    paddingRight: buttonTokens.paddingInlineLg,
    fontSize: buttonTokens.fontSizeLg,
    minHeight: buttonTokens.minHeightLg,
  },
  // States
  disabled: {
    opacity: 0.7,
    cursor: 'not-allowed',
  },
});

/**
 * Button component using React Strict DOM
 *
 * @example
 * ```tsx
 * <Button variant="primary" onClick={() => console.log('clicked')}>
 *   Click me
 * </Button>
 * ```
 */
export function Button({
  children,
  onClick,
  variant = 'primary',
  size = 'medium',
  disabled = false,
  href,
  target,
  rel,
}: ButtonProps) {
  const isNative = Platform.OS !== 'web';
  const styleProps = [
    styles.base,
    styles[variant],
    styles[size],
    disabled && styles.disabled,
  ];

  const handlePress = () => {
    if (disabled) return;
    onClick?.();
    if (href) {
      void Linking.openURL(href);
    }
  };

  if (href && !isNative) {
    return (
      <html.a
        href={href}
        target={target}
        rel={rel}
        style={styleProps}
        aria-disabled={disabled || undefined}
      >
        {children}
      </html.a>
    );
  }

  if (href && isNative) {
    return (
      <html.button
        type="button"
        onClick={handlePress}
        disabled={disabled}
        style={styleProps}
      >
        {children}
      </html.button>
    );
  }

  return (
    <html.button
      onClick={disabled ? undefined : onClick}
      disabled={disabled}
      style={styleProps}
    >
      {children}
    </html.button>
  );
}
