// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './list';

declare global {
  interface HTMLElementTagNameMap {
    'list-box': import('./list').List;
  }
}

