// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './divider';

declare global {
  interface HTMLElementTagNameMap {
    'divider-box': import('./divider').Divider;
  }
}

