// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './dialog-footer';
export * from './dialog-header';
export * from './dialog';

declare global {
  interface HTMLElementTagNameMap {
    'dialog-box': import('./dialog').Dialog;
    'dialog-footer-box': import('./dialog-footer').DialogFooter;
    'dialog-header-box': import('./dialog-header').DialogHeader;
  }
}

