// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './drawer-header';
export * from './drawer';

declare global {
  interface HTMLElementTagNameMap {
    'drawer-box': import('./drawer').Drawer;
    'drawer-header-box': import('./drawer-header').DrawerHeader;
  }
}

