/**
 * Badge component for @box-model/rsd
 *
 * Simple presentational component for status indicators and labels.
 * Uses StyleX tokens generated by StyleDictionary for cross-platform compatibility.
 */
import { css, html } from 'react-strict-dom';
import {
  badgeTokens,
  colorFeedbackTokens,
  typographyRolesTokens,
  typographyTokens,
} from '../tokens/tokens.stylex';

export type BadgeVariant = 'default' | 'success' | 'warning' | 'error' | 'info';
export type BadgeSize = 'small' | 'medium';

export interface BadgeProps {
  /** Badge content */
  children: React.ReactNode;
  /** Visual variant */
  variant?: BadgeVariant;
  /** Badge size */
  size?: BadgeSize;
}

const styles = css.create({
  base: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: badgeTokens.gap,
    // Use individual padding tokens for React Native compatibility
    paddingTop: badgeTokens.paddingBlock,
    paddingBottom: badgeTokens.paddingBlock,
    paddingLeft: badgeTokens.paddingInline,
    paddingRight: badgeTokens.paddingInline,
    fontFamily: typographyRolesTokens.captionFontFamily,
    fontWeight: typographyRolesTokens.captionFontWeight,
    fontSize: typographyRolesTokens.captionFontSize,
    lineHeight: typographyRolesTokens.captionLineHeight,
    letterSpacing: typographyRolesTokens.captionLetterSpacing,
    borderRadius: 0,
  },
  // Variants
  default: {
    backgroundColor: badgeTokens.background,
    color: badgeTokens.text,
  },
  success: {
    backgroundColor: colorFeedbackTokens.successSurface,
    color: colorFeedbackTokens.successText,
  },
  warning: {
    backgroundColor: colorFeedbackTokens.warningSurface,
    color: colorFeedbackTokens.warningText,
  },
  error: {
    backgroundColor: colorFeedbackTokens.dangerSurface,
    color: colorFeedbackTokens.dangerText,
  },
  info: {
    backgroundColor: colorFeedbackTokens.infoSurface,
    color: colorFeedbackTokens.infoText,
  },
  // Sizes
  small: {
    fontSize: typographyTokens.fontSizeXs,
  },
  medium: {
    fontSize: typographyRolesTokens.captionFontSize,
  },
});

/**
 * Badge component using React Strict DOM
 *
 * @example
 * ```tsx
 * <Badge variant="success">Active</Badge>
 * <Badge variant="error" size="small">3</Badge>
 * ```
 */
export function Badge({
  children,
  variant = 'default',
  size = 'medium',
}: BadgeProps) {
  return (
    <html.span
      style={[
        styles.base,
        styles[variant],
        styles[size],
      ]}
    >
      {children}
    </html.span>
  );
}
