// This file is auto-generated by libs/web/generators/tag-name-map.ts. Do not modify manually.

export * from './terminal-line';
export * from './terminal';

declare global {
  interface HTMLElementTagNameMap {
    'terminal-box': import('./terminal').Terminal;
    'terminal-line-box': import('./terminal-line').TerminalLine;
  }
}

